name: GitHub Actions Demo
run-name: GitHub Action Reusable Workflow
on:
  workflow_dispatch:
jobs:
  Basic-Workflow:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Executing Reusable Workflow"
