name: GitHub Actions Reusable Workflow
run-name: GitHub Action Reusable Workflow
on:
  workflow_dispatch:

jobs:
  Basic-Workflow:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Executing Reusable Workflow"
