name: Reusable Workflow Caller

on:
  workflow_dispatch:
  push:

jobs:
  caller-job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Invoking Reusable Workflow
        uses: ./.github/workflows/basic-workflow.yml
