name: Reusable Workflow Caller

on:
  push:

jobs:
  Reusable-caller-job:
    uses: ./.github/workflows/maven-cache.yml
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  Kubernetes-Deployment:
    runs-on: ubuntu-latest
    steps:
     - name: Configure AWS credentials
       uses: aws-actions/configure-aws-credentials@v4
       with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: us-east-2
     - name: Validate AWS Credentials
       run: |
          aws sts get-caller-identity
     - name: Fetch Kube Config from EKS Service and Deploy Pods
       run: |
          aws sts get-caller-identity
          aws eks update-kubeconfig --name fargate-cluster --region us-east-2
          kubectl get deployments -o wide
          kubectl delete -f deployment.yaml
          kubectl apply -f deployment.yaml
          kubectl get deployments -o wide
